package executor

import (
	"context"
	"fmt"
	"tailor/internal/terminal"
	"tailor/pkg/config"
)

// Executor orchestrates the resume tailoring workflow
type Executor struct {
	config   *config.Config
	terminal *terminal.Manager
	ctx      context.Context
}

// New creates a new Executor with the provided configuration
func New(cfg *config.Config) *Executor {
	return &Executor{
		config:   cfg,
		terminal: terminal.NewManager("Starting Tailor"),
		ctx:      context.Background(),
	}
}

// Run executes the complete resume tailoring workflow
func (e *Executor) Run() error {
	e.terminal.Start()
	defer e.terminal.Shutdown()

	// Load inputs
	masterYAML, err := e.loadResume()
	if err != nil {
		return err
	}

	jobDesc, err := e.loadJobDescription()
	if err != nil {
		return err
	}

	// Get changes (and optionally cover letter) from Claude
	changeSet, err := e.analyzeResume(masterYAML, jobDesc)
	if err != nil {
		return err
	}

	// Interactive review of resume changes
	if err := e.reviewChanges(changeSet); err != nil {
		return err
	}

	// Apply and write resume changes
	approvedCount := len(changeSet.GetApprovedChanges())
	if approvedCount == 0 {
		e.terminal.Info("No resume changes approved")
	} else {
		tailoredYAML, err := e.applyChanges(masterYAML, changeSet)
		if err != nil {
			return err
		}

		if err := e.writeOutput(tailoredYAML); err != nil {
			return err
		}
	}

	// Handle cover letter if generated
	if e.config.GenerateCoverLetter {
		if changeSet.HasCoverLetter() {
			if err := e.writeCoverLetter(changeSet); err != nil {
				return err
			}
		} else {
			e.terminal.Warn("Cover letter requested but not generated by API")
		}
	}

	// Final summary
	e.terminal.Section("✓ Tailor complete!")
	fmt.Printf("\nFiles generated:\n")
	if approvedCount > 0 {
		fmt.Printf("  • Resume: %s (%d changes applied)\n", e.config.OutputPath, approvedCount)
	}
	if e.config.GenerateCoverLetter && changeSet.HasCoverLetter() && !e.config.DryRun {
		fmt.Printf("  • Cover Letter: %s\n", e.config.CoverLetterOutputPath)
	}

	if approvedCount > 0 {
		fmt.Printf("\nNext steps:\n")
		fmt.Printf("  1. Review: %s\n", e.config.OutputPath)
		fmt.Printf("  2. Generate PDF: rendercv render %s\n", e.config.OutputPath)
		if e.config.GenerateCoverLetter && changeSet.HasCoverLetter() {
			fmt.Printf("  3. Review cover letter: %s\n", e.config.CoverLetterOutputPath)
		}
	}

	return nil
}
